# Generated by Django 3.0.2 on 2023-08-12 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('df771dd5-a4a8-498e-adbc-672b47b8bcdf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
