# Generated by Django 3.0.2 on 2023-08-12 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20230812_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6fb03ab7-f7cc-4796-b050-b7f53ccd13da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
