# Generated by Django 3.0.2 on 2023-08-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_post_good_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.TextField(max_length=255),
        ),
    ]
