# Generated by Django 3.0.2 on 2023-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0010_auto_20230827_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
    ]
