# Generated by Django 3.0.2 on 2023-08-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0011_post_comment_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_num',
        ),
    ]
