# Generated by Django 3.0.2 on 2023-09-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0013_auto_20230908_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mentions',
        ),
    ]
