# Generated by Django 3.0.2 on 2023-09-09 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0014_remove_post_mentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=20)),
                ('new', models.BooleanField(default=True)),
            ],
        ),
    ]
