# Generated by Django 3.0.2 on 2023-09-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0015_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
