# Generated by Django 3.0.2 on 2023-09-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0018_auto_20230909_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='sns.Post'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_post', to='sns.Post'),
        ),
    ]
