# Generated by Django 3.0.2 on 2023-09-11 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0019_auto_20230911_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('posts', models.ManyToManyField(blank=True, related_name='posts', to='sns.Post')),
            ],
        ),
    ]
