# Generated by Django 3.0.2 on 2023-09-11 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0020_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mention',
            field=models.ManyToManyField(blank=True, related_name='mention', to=settings.AUTH_USER_MODEL),
        ),
    ]
