# Generated by Django 3.0.2 on 2023-09-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0021_post_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, to='sns.Post'),
        ),
    ]
