# Generated by Django 3.0.2 on 2023-09-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0022_auto_20230911_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='name',
            new_name='tag',
        ),
    ]
