# Generated by Django 3.0.2 on 2023-09-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0023_auto_20230912_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tag',
            new_name='name',
        ),
    ]
