# Generated by Django 3.0.2 on 2023-08-12 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0f1f5a3-c675-45e5-a6a9-df9d66c26e79'), editable=False, primary_key=True, serialize=False),
        ),
    ]
