# Generated by Django 3.0.2 on 2023-08-12 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230812_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a3dd8ce-f309-4006-bedd-379b6d4119b2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
