# Generated by Django 3.0.2 on 2023-08-12 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230812_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='SOHbnvD1ADSdESIX', max_length=16, unique=True, verbose_name='usertag'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
