# Generated by Django 3.0.2 on 2023-08-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230813_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='CtwIrOGmFkRoJlhJ', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
