# Generated by Django 3.0.2 on 2023-08-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230815_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='3qGZnBIfVlO66x0j', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
