# Generated by Django 3.0.2 on 2023-08-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230823_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='WQwL73vC8SoG2fiR', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
