# Generated by Django 3.0.2 on 2023-08-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230823_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='3vurBfXK6682kB1W', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
