# Generated by Django 3.0.2 on 2023-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230827_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='nH5EUhh59DIBg9Gm', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
