# Generated by Django 3.0.2 on 2023-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230827_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='FRuolsBmrdpOENaD', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
