# Generated by Django 3.0.2 on 2023-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230830_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='CvRTNRzaLUY7owao', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
