# Generated by Django 3.0.2 on 2023-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230830_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='namename',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='NDdaf3Pu8yJhfwAR', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
