# Generated by Django 3.0.2 on 2023-09-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0012_remove_post_comment_num'),
        ('accounts', '0019_auto_20230908_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='namename',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mentioned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sns.Post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='cFi09NUiDAtzcFVu', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
