# Generated by Django 3.0.2 on 2023-09-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20230908_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mentioned',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(default='3BYuLaPIJqHYi2Qp', max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
