# Generated by Django 3.0.2 on 2023-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20230908_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertag',
            field=models.CharField(max_length=16, unique=True, verbose_name='usertag'),
        ),
    ]
