# Generated by Django 3.0.2 on 2023-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0014_remove_post_mentions'),
        ('accounts', '0023_auto_20230909_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mentioned',
            field=models.ManyToManyField(blank=True, related_name='mentioned', to='sns.Post'),
        ),
    ]
