# Generated by Django 3.0.2 on 2023-09-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_customuser_mentioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mentioned',
        ),
    ]
